# Generated by Django 4.2.4 on 2023-09-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('up_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
